### ISSUE TITLE
function add2(n) {   return n + two    // Feel free to move things around!   const two = 2   return n + two }

### ISSUE THREAD

**Issue by dwmdwm2001910** [learn-co-curriculum/javascript-arithmetic-lab#8] opened 2016-09-12 19:46 UTC

**Comment by AnnJohn** [comment] 2016-09-12 20:13
hi @dwmdwm2001910 could you please be a bit specific about what the issue is or where the problem is and what/how it should be fixed? thanks!

**Comment by AnnJohn** [comment] 2016-09-22 14:24
closing

**Closed as completed by AnnJohn** 2016-09-22 14:24 UTC
Labels: Curriculum
